### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Caumaker** [Hyun-je/pyrplidar#1]
Hi there, thanks for the pyrplidar.
I was searching how begin with RPLIDAR A1M8. And I found your project. It's is very clear and well documented. Congratulations.
I have experiencing some issue when I try to connect to my lidar.
I got the follow crash in every example:

`λ python check_connection.py           
PyRPlidar Info : device is connected   
Traceback (most recent call last):     
  File "check_connection.py", line 33, 
    check_connection()                 
  File "check_connection.py", line 13, 
    info = lidar.get_info()            
  File "C:\Python27\lib\site-packages\p
    discriptor = self.receive_discripto
  File "C:\Python27\lib\site-packages\p
    discriptor = PyRPlidarResponse(self
  File "C:\Python27\lib\site-packages\p
    self.sync_byte1 = raw_bytes[0]     
IndexError: string index out of range  `

Could you help me?
I tried on Windows and Linux already. No successs. Thanks in advance.

**Comment by kuehjialee** [comment]
> Hi there, thanks for the pyrplidar.
> I was searching how begin with RPLIDAR A1M8. And I found your project. It's is very clear and well documented. Congratulations.
> I have experiencing some issue when I try to connect to my lidar.
> I got the follow crash in every example:
> 
> `λ python check_connection.py PyRPlidar Info : device is connected Traceback (most recent call last): File "check_connection.py", line 33, check_connection() File "check_connection.py", line 13, info = lidar.get_info() File "C:\Python27\lib\site-packages\p discriptor = self.receive_discripto File "C:\Python27\lib\site-packages\p discriptor = PyRPlidarResponse(self File "C:\Python27\lib\site-packages\p self.sync_byte1 = raw_bytes[0] IndexError: string index out of range `
> 
> Could you help me?
> I tried on Windows and Linux already. No successs. Thanks in advance.



Hi. I realized that the Baud Rate of 115200 is used in this library. So, instead of using 256000 as stated in the example codes, please change it to 115200. This will solve your problem.

**Comment by adolfoherrera1417** [comment]
Hello, I have been getting this same error and have already changed the Baud Rate to 115200, but that did not seem to help. Any other changes I could make?

**Comment by kuehjialee** [comment]
How about your serial port? Sometimes, your serial port name will change after shutting down. Double check your "Port" and "Baud Rate".

**Comment by irbigturtle** [comment]
Hi, I am having the same issue. I double checked the baud rate and port multiple times. I also reinstalled the driver - no change. Any thoughts? Same model A1M8

**Comment by Ajasra** [comment]
The same problem with the code. With right Baud Rate and com port.

**Comment by Yang-Changhui** [comment]
请问一下，大家这个问题解决了吗

**Comment by Yang-Changhui** [comment]
hi,I met the same problem,I want to know if you solve the problem.If you could help me ,I will appreciate it

**Comment by ZGX010** [comment]
i find   [https://github.com/SkoltechRobotics/rplidar](url)

**Comment by yurikleb** [comment]
Changing the baud to 115200 worked for my RPLIDAR A1M8 on Ubuntu in python3

**Comment by TCIII** [comment]
This works for the A1M8 (all firmware versions) and the A2M8 (latest firmware version) that run a 115,000 baud:

# Setup the RPLidar
PORT_NAME = '/dev/ttyUSB0'
lidar = RPLidar(None, PORT_NAME, timeout=3)

**Comment by kamil52512** [comment]
On Windows 10, modifying a file the pyrplidar_serial.py from library helps.
In line 13 replace:
"self._serial = serial.Serial(port, baudrate, parity=serial.PARITY_NONE, stopbits=serial.STOPBITS_ONE, timeout=timeout, dsrdtr=True)"
to
" self._serial = serial.Serial(port, baudrate, parity=serial.PARITY_NONE, stopbits=serial.STOPBITS_ONE, timeout=timeout, dsrdtr=False)"
